// flow-typed signature: 25ad8f6fc4cbb999125edeebd9cdd4e0
// flow-typed version: <<STUB>>/algoliasearch-helper_v^2.26.1/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'algoliasearch-helper'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'algoliasearch-helper' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'algoliasearch-helper/dist/algoliasearch.helper' {
  declare module.exports: any;
}

declare module 'algoliasearch-helper/dist/algoliasearch.helper.min' {
  declare module.exports: any;
}

declare module 'algoliasearch-helper/src/algoliasearch.helper' {
  declare module.exports: any;
}

declare module 'algoliasearch-helper/src/DerivedHelper/index' {
  declare module.exports: any;
}

declare module 'algoliasearch-helper/src/functions/formatSort' {
  declare module.exports: any;
}

declare module 'algoliasearch-helper/src/functions/valToNumber' {
  declare module.exports: any;
}

declare module 'algoliasearch-helper/src/functions/warnOnce' {
  declare module.exports: any;
}

declare module 'algoliasearch-helper/src/requestBuilder' {
  declare module.exports: any;
}

declare module 'algoliasearch-helper/src/SearchParameters/filterState' {
  declare module.exports: any;
}

declare module 'algoliasearch-helper/src/SearchParameters/index' {
  declare module.exports: any;
}

declare module 'algoliasearch-helper/src/SearchParameters/RefinementList' {
  declare module.exports: any;
}

declare module 'algoliasearch-helper/src/SearchParameters/shortener' {
  declare module.exports: any;
}

declare module 'algoliasearch-helper/src/SearchResults/generate-hierarchical-tree' {
  declare module.exports: any;
}

declare module 'algoliasearch-helper/src/SearchResults/index' {
  declare module.exports: any;
}

declare module 'algoliasearch-helper/src/url' {
  declare module.exports: any;
}

declare module 'algoliasearch-helper/src/version' {
  declare module.exports: any;
}

// Filename aliases
declare module 'algoliasearch-helper/dist/algoliasearch.helper.js' {
  declare module.exports: $Exports<'algoliasearch-helper/dist/algoliasearch.helper'>;
}
declare module 'algoliasearch-helper/dist/algoliasearch.helper.min.js' {
  declare module.exports: $Exports<'algoliasearch-helper/dist/algoliasearch.helper.min'>;
}
declare module 'algoliasearch-helper/index' {
  declare module.exports: $Exports<'algoliasearch-helper'>;
}
declare module 'algoliasearch-helper/index.js' {
  declare module.exports: $Exports<'algoliasearch-helper'>;
}
declare module 'algoliasearch-helper/src/algoliasearch.helper.js' {
  declare module.exports: $Exports<'algoliasearch-helper/src/algoliasearch.helper'>;
}
declare module 'algoliasearch-helper/src/DerivedHelper/index.js' {
  declare module.exports: $Exports<'algoliasearch-helper/src/DerivedHelper/index'>;
}
declare module 'algoliasearch-helper/src/functions/formatSort.js' {
  declare module.exports: $Exports<'algoliasearch-helper/src/functions/formatSort'>;
}
declare module 'algoliasearch-helper/src/functions/valToNumber.js' {
  declare module.exports: $Exports<'algoliasearch-helper/src/functions/valToNumber'>;
}
declare module 'algoliasearch-helper/src/functions/warnOnce.js' {
  declare module.exports: $Exports<'algoliasearch-helper/src/functions/warnOnce'>;
}
declare module 'algoliasearch-helper/src/requestBuilder.js' {
  declare module.exports: $Exports<'algoliasearch-helper/src/requestBuilder'>;
}
declare module 'algoliasearch-helper/src/SearchParameters/filterState.js' {
  declare module.exports: $Exports<'algoliasearch-helper/src/SearchParameters/filterState'>;
}
declare module 'algoliasearch-helper/src/SearchParameters/index.js' {
  declare module.exports: $Exports<'algoliasearch-helper/src/SearchParameters/index'>;
}
declare module 'algoliasearch-helper/src/SearchParameters/RefinementList.js' {
  declare module.exports: $Exports<'algoliasearch-helper/src/SearchParameters/RefinementList'>;
}
declare module 'algoliasearch-helper/src/SearchParameters/shortener.js' {
  declare module.exports: $Exports<'algoliasearch-helper/src/SearchParameters/shortener'>;
}
declare module 'algoliasearch-helper/src/SearchResults/generate-hierarchical-tree.js' {
  declare module.exports: $Exports<'algoliasearch-helper/src/SearchResults/generate-hierarchical-tree'>;
}
declare module 'algoliasearch-helper/src/SearchResults/index.js' {
  declare module.exports: $Exports<'algoliasearch-helper/src/SearchResults/index'>;
}
declare module 'algoliasearch-helper/src/url.js' {
  declare module.exports: $Exports<'algoliasearch-helper/src/url'>;
}
declare module 'algoliasearch-helper/src/version.js' {
  declare module.exports: $Exports<'algoliasearch-helper/src/version'>;
}
