// @flow


// ACTION_TYPES

export const FETCH_REQUEST:'products/FETCH_REQUEST' = 'products/FETCH_REQUEST'
export const FETCH_SUCCESS:'products/FETCH_SUCCESS' = 'products/FETCH_SUCCESS'
export const FETCH_FAILURE:'products/FETCH_FAILURE' = 'products/FETCH_FAILURE'

export const INIT_LIST:'products/INIT_LIST' = 'products/INIT_LIST'
export const FETCH_LIST_REQUEST:'products/FETCH_LIST_REQUEST' = 'products/FETCH_LIST_REQUEST'
export const FETCH_LIST_SUCCESS:'products/FETCH_LIST_SUCCESS' = 'products/FETCH_LIST_SUCCESS'
export const FETCH_LIST_FAILURE:'products/FETCH_LIST_FAILURE' = 'products/FETCH_LIST_FAILURE'
export const TOGGLE_FILTER:'products/TOGGLE_FILTER' = 'products/TOGGLE_FILTER'
export const SET_PRICE_RANGE:'products/SET_PRICE_RANGE' = 'products/SET_PRICE_RANGE'
export const TOGGLE_CATEGORY:'products/TOGGLE_CATEGORY' = 'products/TOGGLE_CATEGORY'
export const SET_CONTEXT:'products/SET_CONTEXT' = 'products/SET_CONTEXT'
export const SET_PAGE:'products/SET_PAGE' = 'products/SET_PAGE'
export const SET_QUERY:'products/SET_QUERY' = 'products/SET_QUERY'
export const TOGGLE_TAG:'products/TOGGLE_TAG' = 'products/TOGGLE_TAG'

export const FETCH_FILTER_OPTIONS_REQUEST:'products/FETCH_FILTER_OPTIONS_REQUEST' = 'products/FETCH_FILTER_OPTIONS_REQUEST'
export const FETCH_FILTER_OPTIONS_SUCCESS:'products/FETCH_FILTER_OPTIONS_SUCCESS' = 'products/FETCH_FILTER_OPTIONS_SUCCESS'
export const FETCH_FILTER_OPTIONS_FAILURE:'products/FETCH_FILTER_OPTIONS_FAILURE' = 'products/FETCH_FILTER_OPTIONS_FAILURE'

export const FETCH_CATEGORY_OPTIONS_REQUEST:'products/FETCH_CATEGORY_OPTIONS_REQUEST' = 'products/FETCH_CATEGORY_OPTIONS_REQUEST'
export const FETCH_CATEGORY_OPTIONS_SUCCESS:'products/FETCH_CATEGORY_OPTIONS_SUCCESS' = 'products/FETCH_CATEGORY_OPTIONS_SUCCESS'
export const FETCH_CATEGORY_OPTIONS_FAILURE:'products/FETCH_CATEGORY_OPTIONS_FAILURE' = 'products/FETCH_CATEGORY_OPTIONS_FAILURE'